blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path("blogs", views.blogs, name='blogs'),
    path('blog/<int:blog_id>/', views.blog, name='blog'),
    
]

murage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mypage.urls')),
    path('blogs/', include('blogs.urls')),
]

mypage/urls.py
from django.urls import path, include
from . import views

app_name = "mypage"
urlpatterns = [
    path('', views.index, name='index'),
    path('software/', views.software, name='software'),
    path('projects/', views.projects, name='projects'),
    path('contact/', views.contact, name='contact'),
    
]

blogs/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    topic = models.CharField(max_length=150)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.topic

# class Entry(models.Model):
#     topic = models.ForeignKey(Blog, on_delete=models.CASCADE)
   

#     class Meta:
#         verbose_name_plural = "entries"

#     def __str__(self):
#         """Return a string represention of the model"""
#         return f"{self.text[:100]}..."




    

mypage/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=300)
    decription = models.TextField()
    

    def __str__(self):
        return self.name

class Software(models.Model):
    title = models.CharField( max_length=50, primary_key=True)
    desc = models.CharField(max_length=100)
    urls = models.CharField( max_length=100)
    

    class Meta:
        db_table = "spiderCollection1"

    def __str__(self):
        return self.title

    

mypage/forms.py
from django import forms
from .models import *

class contactForm(forms.Form):
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=False)
    email_address = forms.EmailField(max_length=150, required=True)
    message = forms.CharField(widget=forms.Textarea, max_length=2000, required=True)
    # class meta:
    #     model = contact
    #     fields = ['text']
    #     labels = {'text': ''}

blogs/views.py
from django.shortcuts import render
from .models import *

# Create your views here.
def blogs(request):
    # contains what to display on blogs page
    blogs = Blog.objects.order_by('date_added')
    # entries = Entry.objects.order_by('topic')?
    context = {'blogs': blogs}
    return render(request, 'mypage/blogs.html', context)

def blog(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    context = {'blog': blog}
    return render(request, 'mypage/blog.html', context)

mypage/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail, BadHeaderError, get_connection
from .forms import *
from django.http import HttpResponse

# Create your views here.
def index(request):
    context= {}
    return render(request, 'mypage/index.html')

def software(request):
    
    context={}
    return render(request, 'mypage/software.html')

def projects(request):
    context={}
    return render(request, 'mypage/projects.html')



def contact(request):
    form = contactForm()
    if request.method == 'POST':
        form = contactForm(request.POST)
        # validate form
        if form.is_valid():
            subject = "Website inquiry"
            body = {
                'first_name': form.cleaned_data['first_name'],
                'last_name': form.cleaned_data['last_name'],
                'email': form.cleaned_data['email_address'],
                'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, body['email'], ['dennismurage97@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found')
            return redirect('mypage:index')

    context={'form': form}
    return render(request, 'mypage/contact.html', context)

mypage/templates/mypage/base.html
{% load bootstrap4 %}
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    
    <title>Murage</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>

     
      <div class='main-page'>
        {% block content %}

        {% endblock content %}
    </div>

          
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <script src="static/main.js"></script> 
</body>
</html>

mypage/templates/mypage/blog.html
{% extends 'mypage/base.html' %}

{% block content %}
{% include 'mypage/navbar.html' %}
<br>
<br>
<br>
<div class="container">
    <h4 class="ut header-text">{{blog.topic}}</h4>
    <hr>
    <p class="blog-text" id="bt">{{blog.text|linebreaks}}</p>


</div>

{% endblock content %}

mypage/templates/mypage/blogs.html
{% extends 'mypage/base.html' %}
{% load static %}
{% load bootstrap4 %}


{% block content %}
{% include 'mypage/navbar.html' %}

<br>
<br>
<br>

<div class='icons' id='bg-icons' style="background: black;">
    <ul>
        <li><a href="#" ><img src=" {% static 'images/email.png'%}" alt=""></a></li>
        <li><a href="https://github.com/javaGhost1" target="_blank"><img src="{% static 'images/github.png'%}" alt=""></a></li>
        <li><a href="https://twitter.com/home" target="_blank"><img src="{% static 'images/twitter_transparent.png' %}" alt=""></a></li>
        <li><a href="https://www.instagram.com/njerufreeman/" target="_blank"><img src="{% static 'images/instagram.png'%}" alt=""></a></li>
    </ul>
</div> 

<div class="container">
    <div class='card mb-3' style="border:none;">
        <ul>
            {% for blog in blogs %}
                <li>
                    <a class='blog-link' href={% url 'blogs:blog' blog.id%}>
                        <h4 class="header-text">{{blog.topic}}</h4>
                        <p>{{blog.text|safe|truncatewords:25}}</p>
                        <p>{{blog.date_added|date:'M d, Y'}}</p>
                       
                        
                    </a>
                    <br>
                </li>
            
            {%empty%}
                <li> No blogs yet</li>
            {% endfor %}
        </ul>
    </div>

</div>
{% include 'mypage/footer.html' %}
{% endblock content %}

mypage/templates/mypage/contact.html
{% extends 'mypage/base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
{% include 'mypage/navbar.html' %}
    <div class='contact' style="padding:5px;">
        <h4 style=" padding-top: 80px;">Message me for any inquiry.</h4>
        <p>
        Please enter your name, email address and message.
        I will be happy to contact you directly and answer your questions.
        </p>
    
    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
        <input type="hidden" name='next' value="{% url 'mypage:index'%}"/>
    </form>
</div>
    <br>
    <div>
        <footer class="footer container-fluid">
            <div class="container footer-content">
                <p class="footerText" style="color: #fff;">STAY CONNECTED</p>
                <div class="icons">
                <ul>
                    <li><a href="#"><img src=" {% static 'images/email.png'%}" alt=""></a></li>
                    <li><a href="#"><img src="{% static 'images/github.png'%}" alt=""></a></li>
                    <li><a href="#"><img src="{% static 'images/twitter_transparent.png' %}" alt=""></a></li>
                    <li><a href="#"><img src="{% static 'images/instagram.png'%}" alt=""></a></li>
                </ul>
                </div>
            </div>
        </footer>
    </div>



{% endblock content %}

mypage/templates/mypage/footer.html
{% extends 'mypage/base.html' %}
{% load static %}

{% block content %}
<div>
    <footer class="footer container-fluid">
        <div class="container footer-content">
            <p class="footerText">STAY CONNECTED</p>
            <div class="icons">
                <ul>
                    <li><a href="#" ><img src=" {% static 'images/email.png'%}" alt=""></a></li>
                    <li><a href="https://github.com/javaGhost1" target="_blank"><img src="{% static 'images/github.png'%}" alt=""></a></li>
                    <li><a href="https://twitter.com/home" target="_blank"><img src="{% static 'images/twitter_transparent.png' %}" alt=""></a></li>
                    <li><a href="https://www.instagram.com/njerufreeman/" target="_blank"><img src="{% static 'images/instagram.png'%}" alt=""></a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

{% endblock content %}

mypage/templates/mypage/index.html
{% extends 'mypage/base.html'%}
{% load static %}
{% load bootstrap4 %}

{% block content%}
{% include 'mypage/navbar.html' %}

   <main id="main-body" style = "background-image: url({% static '/images/image2.jpg' %}); ">

            <div class='home-banner'> 
                <h3 id="msg" class="banner-msg">Dennis <br> Murage</h3>

            
                <p class="banner-msg">Self-learning software and electrical engineering<br> through research & development.</p>   
            </div>
            <div class="icons">
                <ul>
                    <li><a href="{% url 'mypage:contact'%}" ><img src="{% static 'images/email.png'%}" alt="you"></a></li>
                    <li><a href="https://github.com/javaGhost1" target="_blank"><img src="{% static 'images/github.png'%}" alt=""></a></li>
                    <li><a href="https://twitter.com/NjeruFreeman" target="_blank"><img src="{% static 'images/twitter_transparent.png' %}" alt=""></a></li>
                    <li><a href="https://www.instagram.com/njerufreeman/" target="_blank"><img src="{% static 'images/instagram.png'%}" alt=""></a></li>
                </ul>
            </div>
            <a class="ct-btn-scroll ct-js-btn-scroll" href="#section2"><img alt="Arrow Down Icon" src="{% static 'images/arrow-down-1.png' %}"></a>
    </main>
<section id="section2" class="my-work">
    <h3 id="msg">My Work</h3>
    <p>I am Dennis Murage, a curious web developer. I am passionate about web development and have spent my last six years learning different technologies. I am proficient in Html, Css, Python and Django. I've also worked with Javascript and it's libraries. I exist to try out different activities that interest me. I spend a lot of time building software and electronics, but there’s also a lot more to it. I’ve been working on a blog format to document the logic, reasoning, and problems encountered during the process of learning engineering. A combination of innovation and storytelling.</p>
    <div class="list-panel">
        <div class="col-lg-3">
            <h5>Software Development</h5>
            <ul>
                <li>Python Automation.</li>
                <li>2D Game Development.</li>
                <li> Data Visualization using Matplotlib and Plotly.</li>
                <li>Low level/embedded IoT programming</li>
                <li>Cloud computing, microservices, APIs, full stack web apps</li>
            </ul>
        </div>
        <div class="col-lg-3">
            <h5>Electronics</h5>
            <ul>
                <li>LED</li>
                <li>Robotics, batteries, embedded systems</li>
                <li>Trying not blow myself up by teaching myself IEE is quite exciting</li>
            </ul>
        </div>
        <div class="col-lg-3">
            <h5>Community Contribution</h5>
            <ul>
                <li>Blogging about my unique encounters</li>
                <li>Open source projects on Github</li>
            </ul>
        </div>
    </div>
    <div class="container-fluid">
        <div class="container" id="popular">
            <h5 class="h5spacing" style="color: black;">Popular Projects</h5>
            <div class="table-responsive">
                <div class="django-bootstrap-table">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Title</th>
                                <th scope="col">Description</th>
                                <th scope="col">Language</th> 
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">1</th>
                                    <td>Alien Invasion</td>
                                    <td>A game that the player is a rocket whose task is to shoot down aliens.</td>
                                    <td>Python</td>


                            </tr>
                            <tr>
                                <th scope="row">2</th>
                                <td>Data Visualization</td>
                                <td>A
                                    self-contained program that generates a visu-
                                    alization based on data that it retrieves. The
                                    program uses a API to automatically request specific informa-
                                    tion from a website.</td>
                                <td>Python</td>

                            </tr>
                            <tr>
                                    <th scope="row">3</th>
                                    <td>
                                        <a target="_blank" href="https://guarded-cove-79207.herokuapp.com/">
                                        
                                        Code Vibes Blogging site
                                        </a>
                                    </td>
                                    <td>A simple blog web application. I implemented all the necessary views for users to register, log in, log out,
                                        edit their password, and reset their password. Built a model for custom user
                                        profiles and created a custom authentication backend to let users log in to
                                        the site using their email address. We also added social authentication to the
                                        site so that users can use their existing Facebook, Twitter, or Google account to
                                        log in.</td>
                                    <td>Django</td>
                            </tr>
                            <tr>
                                <th scope="row">4</th>
                                <td>
                                    <a target="_blank" href='https://fast-reef-57613.herokuapp.com/blog/'>
                                    
                                    Mwakenya Blogging site</td>
                                    </a>
                                <td>A web application that uses custom Django template tags and filters
                                    to provide templates with a custom functionality. I created a sitemap for
                                    search engines to crawl the site and an RSS feed for users to subscribe to this
                                    blog. I then built a search engine for this blog using the full-text search engine
                                    of PostgreSQL</td>
                                <td>Django</td>
                             
                            </tr>
                            <tr>
                                <th scope="row">5</th>
                                <td>Search results engine</td>
                                <td>Search engine</td>
                                <td>Python</td>
                            </tr>
                            <tr>
                                <th scope="row">6</th>
                                <td>Expense Tracker</td>
                                <td>A daily expense tracker</td>
                                <td>Python</td>
                            </tr>
                            <tr>
                                <th scope="row">7</th>
                                <td>Facial recognition AI</td>
                                <td>Face recognition app</td>
                                <td>Python</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- <div class="container">
        <h5 class="h5spacing">Future Ventures(Teach myself 2021)</h5>
        <ul>
            <li>Scalable distributed systems(infrastructure, networks, microservices</li>
            <li>Machine Learning</li>
            <li>Image/Video processing</li>
            <li>Security</li>
            <li>File servers/ personal datacenters/ NAS</li>
            <li>Blockchain</li>
            <li>Embedded Systems</li>
            <li>Electrical engineering</li>
            <li>Toasting bread instatly</li>
        </ul>
        <br>
        <p>
            I have many intersts besides technology that I may share in a similar approach. You can read more about my technology stack on the software page.
        </p>

    </div> -->
    {% include 'mypage/footer.html' %}

    </section>

{% endblock content%}

mypage/templates/mypage/navbar.html
{% extends 'mypage/base.html' %}
{% load static %}

{% block content %}
<nav id="global-nav" class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: rgb(240, 240, 240);">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'mypage:index'%}">MURAGE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
         
          <li class="nav-item" id="nav-item">
            <a class="nav-link" id="nav-item" href="{% url "mypage:software"%}">Software</a>
          </li>
         
          <li class="nav-item" id="nav-item">
            <a class="nav-link" href="{% url 'blogs:blogs'%}">Blogs</a>
          </li>
          <li class="nav-item" id="nav-item">
            <a class="nav-link" href="{% url 'mypage:contact'%}">Contact</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

{% endblock content %}

mypage/templates/mypage/software.html
{% extends 'mypage/base.html' %}

{% block content %}
{% include 'mypage/navbar.html' %}
<div  class='table-responsive'>
    <h2 class="banner-msg" style="top: 10px;">Software Repository</h2>

    <table class="table">
        <caption>List of Projects</caption>
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title:</th>
            <th scope="col">Description:</th>
            <th scope="col">Language:</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>A-Pathfinding-Visualization</td>
            <td>Algorithm in java</td>
            <td>Java</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Personal-Website</td>
            <td>Django version</td>
            <td>Django</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Air-Conditioner-Arduino</td>
            <td>When your AC doesn't work.. </td>
            <td>Arduino</td>
          </tr>
        </tbody>
      </table>

</div>
{% include 'mypage/footer.html' %}
{% endblock content %}}